matrix:
    include:
        - os: linux
          dist: bionic
          language: c
          env: BUILD_TYPE=linux
        - os: linux
          dist: bionic
          language: c
          env: BUILD_TYPE=windows
        - os: linux
          dist: bionic
          language: c
          sudo: required
          env: BUILD_TYPE=flatpak
#        - os: linux
#          dist: bionic
#          language: c
#          env: BUILD_TYPE=snap
        - os: osx
          osx_image: xcode11.2
          sudo: required
          language: c
          env: BUILD_TYPE=macos PATH=/usr/local/opt/gettext/bin:$PATH

services:
    - docker

addons:
  apt:
    packages:
        - libgtk-3-dev
        - libao-dev
        - libmpg123-dev
        - meson
        - ninja-build
        - gettext
        - flatpak-builder
  snaps:
      - name: snapcraft
        confinement: classic
      - name: multipass
        confinement: classic
        channel: edge
  homebrew:
    packages:
        - gtk+3
        - libao
        - mpg123
        - meson
        - ninja
        - gettext

deploy:
  provider: releases
  api_key:
    secure: MJ/lh4chzgsbEdAMAF1fCgqT+EHmeKInH0IdB6HQ5nYQTslg9/XyqA2IkAJlfY8EoBrjWe1NilrwCXd7Yrn7a0k3q1PZfeYfU9fOpiBgquRFtigprrelcj3k+ptl8lm8DBOdHqU3oG4rJRf6hRcg8D65ij/OmUZ3TMj3uvmtvQ4hAciYz7aGNrzB9hd+JUO18+buLQO4P84HLbiBA5opI0OXu8eZHnjWD2xGzPReswroUUZY9WSlG5nYBM9U18y8iXAi5WEl8aI1Dt4+DmZR/DRn4KhRf7/VmRKo0x3mEZTd7e+oBK6BOgX4PmB/mekbLqmuH+qgdnbNnvbY1qPjKRW+4C/Q4gyLKSddyg5otDCgGFqzQ/cCPnVwzTIdCwbqBJh9u8Loe9XW1MzH0rE4//K+GVy+3gZ3/P9nJVXSdLK3oSZRKBW0mtT5ZBjZ4yH7gNzXvWRBBiA1umqRiCZKDOto1pW8rm7A0o/pjvvqWRzERvnhXv3Rdb4CB24oOJSrgXoTeubGQtjvWei706b/EkxYOvXWXTB7JzmwiFIv5WBzv0RN20CQL+f6OuxxxfizVj/SbSv4ranrE4ajVC4M7RLyhm/c+39CmKNZUGMzFUcvb7c/bSI5RZ+3QgmJCYMOVHSSO3T6ty00PEZGvFkGjffU10q/id3/fRdHD/YOUEw=
  file: dist/*
  file_glob: true
  on:
    tags: true
  skip_cleanup: true

script:
    - scripts/build.sh $BUILD_TYPE
