matrix:
    include:
        - os: linux
          dist: bionic
          language: c
          env: BUILD_TYPE=linux
        - os: linux
          dist: bionic
          language: c
          env: BUILD_TYPE=windows CONFIGURE_SCRIPT="docker build -t wavbreaker-win32-build scripts/win32" BUILD_SCRIPT="sh scripts/win32/run-build.sh"
        - os: osx
          osx_image: xcode11.2
          sudo: required
          language: c
          env: BUILD_TYPE=macos PATH=/usr/local/opt/gettext/bin:$PATH

services:
    - docker

addons:
  apt:
    packages:
        - libgtk-3-dev
        - libao-dev
        - libmpg123-dev
        - meson
        - ninja-build
        - gettext
  homebrew:
    packages:
        - gtk+3
        - libao
        - mpg123
        - meson
        - ninja
        - gettext

script:
    - ${CONFIGURE_SCRIPT:-meson build}
    - ${BUILD_SCRIPT:-ninja -C build -v}
