matrix:
    include:
        - os: linux
          dist: bionic
          language: c
        - os: osx
          osx_image: xcode11.2
          sudo: required
          language: c

addons:
  apt:
    packages:
        - libgtk-3-dev
        - libao-dev
        - libmpg123-dev
        - meson
        - ninja-build
  homebrew:
    packages:
        - gtk+3
        - libao
        - mpg123
        - meson
        - ninja

script:
    - meson build
    - ninja -C build
