matrix:
    include:
        - os: linux
          dist: bionic
          language: c
        - os: osx
          osx_image: xcode11.2
          sudo: required
          language: c
          env: PATH=/usr/local/opt/gettext/bin:/usr/local/bin:/usr/bin:/bin:$PATH

addons:
  apt:
    packages:
        - libgtk-3-dev
        - libao-dev
        - libmpg123-dev
        - meson
        - ninja-build
        - gettext
  homebrew:
    packages:
        - gtk+3
        - libao
        - mpg123
        - meson
        - ninja
        - gettext

script:
    - meson build
    - ninja -C build
