matrix:
    include:
        - os: linux
          dist: bionic
          language: c
        - os: osx
          osx_image: xcode11.2
          sudo: required
          language: c

addons:
  apt:
    packages:
        - libgtk-3-dev
        - libao-dev
        - libmpg123-dev
  homebrew:
    packages:
        - gtk+3
        - libao
        - mpg123

script:
    - ./autogen.sh
    - make
